"""add bilingual columns to questions and choices

Revision ID: 5d5329ea22f1
Revises: db3251323fc3
Create Date: 2026-03-07 16:49:41.099875

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d5329ea22f1"
down_revision: str | Sequence[str] | None = "db3251323fc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("choices", sa.Column("text_en", sa.Text(), nullable=False))
    op.add_column("choices", sa.Column("text_zh", sa.Text(), nullable=True))
    op.drop_column("choices", "text")
    op.add_column("questions", sa.Column("stem_en", sa.Text(), nullable=False))
    op.add_column("questions", sa.Column("stem_zh", sa.Text(), nullable=False))
    op.add_column("questions", sa.Column("explanation_en", sa.Text(), nullable=True))
    op.add_column("questions", sa.Column("explanation_zh", sa.Text(), nullable=True))
    op.drop_column("questions", "explanation")
    op.drop_column("questions", "stem")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("stem", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "questions",
        sa.Column("explanation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("questions", "explanation_zh")
    op.drop_column("questions", "explanation_en")
    op.drop_column("questions", "stem_zh")
    op.drop_column("questions", "stem_en")
    op.add_column("choices", sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column("choices", "text_zh")
    op.drop_column("choices", "text_en")
    # ### end Alembic commands ###
